export const MOCK_DATA = {
  search: {
    status: "OK",
    request_id: "35bbed7f-91d2-44a6-908b-abd18508f068",
    parameters: {
      query: "react developer",
      page: 1,
      num_pages: 1,
    },
    data: [
      {
        employer_name: "Fortified Insight",
        employer_logo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1QAHzXXq6yBgMaNVaDvvyryTyTXG849RBEHNl&s=0",
        employer_website: null,
        employer_company_type: null,
        job_publisher: "LinkedIn",
        job_id: "kIPcPX8_lD1LE75OAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "React Developer",
        job_apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-at-fortified-insight-3726956489",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.6581,
        apply_options: [
          {
            publisher: "LinkedIn",
            apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-fortified-insight-3726956489",
            is_direct: false,
          },
          {
            publisher: "ZipRecruiter",
            apply_link:
              "https://www.ziprecruiter.com/c/Snakorpio-Group-Inc./Job/[FULLY-REMOTE]-React-Developer/-in-New-York,NY?jid=2ec8dc94a2cf0d1f",
            is_direct: true,
          },
        ],
        job_description:
          "• Preferred East Coast Hours*\n\nFortified Insight offers a rapidly expanding suite of SaaS products which bring awareness to enterprises around the financial and environmental impact of technology. We are seeking a highly skilled Senior React Developer to join our team and play a crucial role in driving our web development initiatives forward. If you are passionate about creating cutting-edge web applications, solving complex problems, and working in a collaborative team environment, we want to hear from you.\n\nFortified Insight is an equal opportunity employer. Eligible candidates must provide evidence of legal working status for any employer in the U.S.\n\nJob Overview\n\nAs a Senior React Developer at Fortified Insight, you will lead the development of our web application and contribute to the overall architecture and technical direction. You will work closely with our product team, designers, and other developers to deliver high-quality and scalable web solutions.\n\nKey Responsibilities\n\nAs a Senior React developer, you will:\n\nFront-End Development:\n• Lead the development of a dynamic and responsive portal with sophisticated dashboards utilizing the React JS library.\n\nArchitecture and Design:\n• Collaborate with the team to create robust and scalable architecture, ensuring the performance and usability of web applications.\n• Translate Figma designs and wireframes into high-quality code.\n• Develop reusable components and front-end libraries for future use.\n\nSupport:\n• Maintain and enhance the portal based on feedback and analytics.\n• Collaboration:\n• Collaborate closely with cross-functional teams, including designers, backend developers, and stakeholders, to ensure seamless integration and the realization of the envisioned functionalities.\n• Ensure the technical feasibility of UI/UX designs.\n\nOptimization:\n• Optimize applications for maximum speed and scalability, keeping up to date with industry trends and best practices.\n\nCode Review:\n• Review and provide constructive feedback on code written by team members, ensuring code quality and best practices.\n\nTesting:\n• Write and maintain unit tests and end-to-end tests to ensure the reliability of the web application.\n\nDocumentation:\n• Assist in the creation of technical documentation and user manuals.\n\nQualifications\n\nRequired Skills:\n• 5+ years of proven experience in React JS development as a Senior Developer, including a deep understanding of React state management libraries such as Redux or Context API.\n• Experience with popular React workflows (such as Flux or Redux) and routing libraries (like React Router).\n• Proficiency in front-end development languages and tools such as HTML5, CSS3, JavaScript/TypeScript, and webpack.\n• Strong understanding of RESTful APIs and modern authorization mechanisms, such as JSON Web Token.\n• Experience in responsive design principles and implementing complex visualizations using Elastic UI and Apex charts libraries.\n• Familiarity with version control systems (e.g., Git) and collaborative development workflows.\n• Proficiency with browser testing and debugging.\n\nPreferred Skills:\n• Experience with back-end API development frameworks, such as Node.js or ASP.NET is a plus.\n• Previous experience with building dashboards and portals.\n• Knowledge of a CSS pre-processor like SASS or LESS.\n\nPersonal Attributes:\n• Excellent problem-solving skills.\n• Excellent attention to detail.\n• Ability to work autonomously and as part of a team.\n• Excellent communication and interpersonal skills.\n• Excellent English.\n\nWork Environment\n• We are a 100% remote company\n• Occasional travel possible",
        job_is_remote: true,
        job_posted_at_timestamp: 1696266219,
        job_posted_at_datetime_utc: "2023-10-02T17:03:39.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=kIPcPX8_lD1LE75OAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2024-03-30T17:03:39.000Z",
        job_offer_expiration_timestamp: 1711818219,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 60,
          experience_mentioned: true,
          experience_preferred: true,
        },
        job_required_skills: [
          "React.js",
          "API Development",
          "Front-End Development",
          "Redux.js",
          "TypeScript",
          "Responsive Web Design",
          "JavaScript",
          "HTML5",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: true,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "5+ years of proven experience in React JS development as a Senior Developer, including a deep understanding of React state management libraries such as Redux or Context API",
            "Experience with popular React workflows (such as Flux or Redux) and routing libraries (like React Router)",
            "Proficiency in front-end development languages and tools such as HTML5, CSS3, JavaScript/TypeScript, and webpack",
            "Strong understanding of RESTful APIs and modern authorization mechanisms, such as JSON Web Token",
            "Experience in responsive design principles and implementing complex visualizations using Elastic UI and Apex charts libraries",
            "Familiarity with version control systems (e.g., Git) and collaborative development workflows",
            "Proficiency with browser testing and debugging",
            "Previous experience with building dashboards and portals",
            "Knowledge of a CSS pre-processor like SASS or LESS",
            "Excellent problem-solving skills",
            "Excellent attention to detail",
            "Ability to work autonomously and as part of a team",
            "Excellent communication and interpersonal skills",
            "Excellent English",
          ],
          Responsibilities: [
            "As a Senior React Developer at Fortified Insight, you will lead the development of our web application and contribute to the overall architecture and technical direction",
            "You will work closely with our product team, designers, and other developers to deliver high-quality and scalable web solutions",
            "Lead the development of a dynamic and responsive portal with sophisticated dashboards utilizing the React JS library",
            "Collaborate with the team to create robust and scalable architecture, ensuring the performance and usability of web applications",
            "Translate Figma designs and wireframes into high-quality code",
            "Develop reusable components and front-end libraries for future use",
            "Maintain and enhance the portal based on feedback and analytics",
            "Collaborate closely with cross-functional teams, including designers, backend developers, and stakeholders, to ensure seamless integration and the realization of the envisioned functionalities",
            "Ensure the technical feasibility of UI/UX designs",
            "Optimize applications for maximum speed and scalability, keeping up to date with industry trends and best practices",
            "Review and provide constructive feedback on code written by team members, ensuring code quality and best practices",
            "Write and maintain unit tests and end-to-end tests to ensure the reliability of the web application",
            "Assist in the creation of technical documentation and user manuals",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
      },
      {
        employer_name: "Abbott Laboratories",
        employer_logo:
          "https://images.forbes.com/media/lists/companies/abbott-laboratories_416x416.jpg",
        employer_website: "http://www.abbott.com",
        employer_company_type: "Manufacturing",
        job_publisher: "Abbott Jobs",
        job_id: "-gOXGwz2UFRYUKz6AAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Mobile React Developer",
        job_apply_link:
          "https://www.jobs.abbott/us/en/job/31048396/Mobile-React-Developer",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.8078,
        apply_options: [
          {
            publisher: "Abbott Jobs",
            apply_link:
              "https://www.jobs.abbott/us/en/job/31048396/Mobile-React-Developer",
            is_direct: false,
          },
          {
            publisher: "BeBee",
            apply_link:
              "https://us.bebee.com/job/20230916-441aba92f42ff96ebdd6f25e9e0190a4",
            is_direct: false,
          },
          {
            publisher: "SWE Career Center - Society Of Women Engineers",
            apply_link:
              "https://careers.swe.org/job/mobile-react-developer/70630561/",
            is_direct: false,
          },
          {
            publisher: "Adzuna",
            apply_link: "https://www.adzuna.com/details/4312947252",
            is_direct: false,
          },
          {
            publisher: "Arkiv",
            apply_link:
              "https://arkiv.co/job-library/job/mobile-developer-architect-react-at-abbott-laboratories-bend-or-YTNJRVgzRERvRFRqVG1Cd01pT2hWRWRuWEE9PQ==",
            is_direct: false,
          },
        ],
        job_description:
          "Abbott is a global healthcare leader that helps people live more fully at all stages of life. Our portfolio of life-changing technologies spans the spectrum of healthcare, with leading businesses and products in diagnostics, medical devices, nutritionals and branded generic medicines. Our 115,000 colleagues serve people in more than 160 countries.\n\nAbout Abbott\n\nAbbott is a global healthcare leader, creating breakthrough science to improve people’s health. We’re always looking towards the future, anticipating changes in medical science and technology.\n\nWorking at Abbott\n\nAt Abbott, you can do work that matters, grow, and learn, care for yourself and family, be your true self and live a full life. You’ll also have access to:\n\n· Career development with an international company where you can grow the career you dream of.\n\n· Free medical coverage for employees* via the Health Investment Plan (HIP) PPO\n\n· An excellent retirement savings plan with high employer contribution\n\n· Tuition reimbursement, the Freedom 2 Save student debt program and FreeU education benefit - an affordable and convenient path to getting a bachelor’s degree.\n\n· A company recognized as a great place to work in dozens of countries around the world and named one of the most admired companies in the world by Fortune.\n\n· A company that is recognized as one of the best big companies to work for as well as a best place to work for diversity, working mothers, female executives, and scientists.\n\n#software #mobile #React #OneTrust #TrustArc\n\nThe Opportunity\n\nYou will work with a modern tech stack on mobile and cloud platform that strives to improve the health and well-being of users in over 49 countries. The core platform consists of systems housed in a large-scale environment responsible for processing billions of tasks every day. The candidate should have strong leadership ability and bring a passion for software engineering to help shape the direction of the team. Highly sought-after qualities include versatility and a desire to continuously learn, improve, and empower other team members. Candidate will support building scalable, highly available, efficient, and secure software solutions for medical devices.\n\nWhat You'll Work On\n• Architect, design and implement Software Solutions for Mobile platforms\n• Focused on Mobile platform using React-Native\n• Support software development and architecture best practices across multiple projects\n• Design and implement services and components for supported architectures\n• Support Mobile Development and Architecture using Hybrid Technologies;React Native, Kotlin Multiplatform Mobile as well as Native Technologies Swift, Kotlin\n• Architect, design and implement the cybersecurity of the supported systems\n• Identify and solve design and technology issues within the current systems\n• Design, Improve and Support product test, build and deployment processed and pipelines\n• Collaborate with internal and external partners to design, develop and integrate with APIs that empower users to share and utilize their medical data in partner systems\n• Design and implement unit testable code that is highly maintainable solutions\n• Collaborate with both internal and external team members to shape and define API contracts\n• Ensure performance, uptime, and scale, maintaining high standards of code quality and thoughtful design\n• Create software architecture and design documentation for the supported solutions and overall best practices and patterns\n• Support solution groups with technical planning, design, and code reviews including peer code review of Pull Request\n• Provide Architecture and Technical Knowledge training and support for the solution groups\n• Develop good working relations with the other solution teams and groups, such as Engineering, Marketing, Product, Test, QA\n• Stay current with emerging trends, making recommendations as needed to help the organization innovate\n\nRequired Qualifications\n• A Bachelor's Degree in Computer Science, Information Technology, or other relevant field with 6+ years' experience or equivalent work experience\n• Familiar with architectures principles, patterns, framework and blueprint\n• Proven experience with architecture and design for mobile, data and/or cloud systems\n• Must have in-depth experience with React Native\n• In-depth knowledge of Turbo-Modules, Fabric, Hermes, React Multi-Threading\n• Knowledge of React Native applications build process\n• Proved Experience with mobile technologies and languages for iOS and Android: Swift, Kotlin, JNI, C/C++ (on mobile)\n• Familiar with data architecture and design practices for mobile solutions\n• Familiar with Analytics Products; Firebase, Segment\n• Preferred experience with CICD Products such as AzureDevOps, CircleCI, Harness, Jenkins, Fastlane, Sentry\n• Preferred experience with Deployment Support Products; Microsoft App Center, TestFlight, PlayStore\n• Preferred experience with Development Support Products; Flipper, Crashlytics, Code Analytics\n• Familiar with Cybersecurity best practices and solutions for supported architecture. Familiar with cryptography concepts\n• Preferred experience with application security aspects of obfuscation and code protection\n• Proven experience implementing mobile solutions and components\n• Preferred to have familiarity with multiple operating systems; iOS, Android, MacOS, Linux, Windows\n• Experience with documenting architectural and deign decisions\n• Experience with working and supporting with multiple development team members\n• Preferred experience with implementation/configuration with Authentication and Access management solutions such as Okta/Auth0, Consent management solutions such as OneTrust/TrustArc\n\nApply Now\n• Participants who complete a short wellness assessment qualify for FREE coverage in our HIP PPO medical plan. Free coverage applies in the next calendar year.\n\nLearn more about our health and wellness benefits, which provide the security to help you and your family live full lives: www.abbottbenefits.com\n\nFollow your career aspirations to Abbott for diverse opportunities with a company that can help you build your future and live your best life. Abbott is an Equal Opportunity Employer, committed to employee diversity.\n\nConnect with us at www.abbott.com, on Facebook at www.facebook.com/Abbott and on Twitter @AbbottNews and @AbbottGlobal.\n\nThe base pay for this position is $90,700.00 – $181,300.00. In specific locations, the pay range may vary from the range posted.",
        job_is_remote: false,
        job_posted_at_timestamp: 1687996800,
        job_posted_at_datetime_utc: "2023-06-29T00:00:00.000Z",
        job_city: "Bend",
        job_state: "OR",
        job_country: "US",
        job_latitude: 44.058174,
        job_longitude: -121.31531,
        job_benefits: ["health_insurance", "retirement_savings"],
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=-gOXGwz2UFRYUKz6AAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: null,
        job_offer_expiration_timestamp: null,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 72,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: [
          "information technology",
          "android",
          "mobile development",
          "ios",
          "mobile platforms",
          "swift",
          "api",
          "computer science",
          "software solutions",
          "mobile technologies",
          "cicd",
          "linux",
          "cloud platform",
          "jenkins",
          "applications",
          "firebase",
          "software development",
          "hybrid",
          "jni",
          "software engineering",
          "analytics",
          "authentication",
          "react",
          "microsoft app center",
          "azuredevops",
          "data architecture",
          "okta",
          "software architecture",
          "kotlin",
          "architecture",
          "Website Development - Developer",
          "Groovy Developer",
          "Social Media Solutions Consultant & Social Strategist",
          "Project Lead & User Experience & User Interface Developer",
          "Internship - Mobile Applications Developer",
          "Salesforce Pre-Sales Consultant",
          "Web Development Consultant",
          "Information Technology Applications Analyst & UX & UI Designer",
          "Shopify Developer",
          "Mobile Applications Developer",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: true,
          degree_preferred: true,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "Focused on Mobile platform using React-Native",
            "A Bachelor's Degree in Computer Science, Information Technology, or other relevant field with 6+ years' experience or equivalent work experience",
            "Familiar with architectures principles, patterns, framework and blueprint",
            "Proven experience with architecture and design for mobile, data and/or cloud systems",
            "Must have in-depth experience with React Native",
            "In-depth knowledge of Turbo-Modules, Fabric, Hermes, React Multi-Threading",
            "Knowledge of React Native applications build process",
            "Proved Experience with mobile technologies and languages for iOS and Android: Swift, Kotlin, JNI, C/C++ (on mobile)",
            "Familiar with data architecture and design practices for mobile solutions",
            "Familiar with Analytics Products; Firebase, Segment",
            "Familiar with Cybersecurity best practices and solutions for supported architecture",
            "Familiar with cryptography concepts",
            "Proven experience implementing mobile solutions and components",
            "Experience with documenting architectural and deign decisions",
            "Experience with working and supporting with multiple development team members",
          ],
          Responsibilities: [
            "Architect, design and implement Software Solutions for Mobile platforms",
            "Design and implement services and components for supported architectures",
            "Architect, design and implement the cybersecurity of the supported systems",
            "Identify and solve design and technology issues within the current systems",
            "Design, Improve and Support product test, build and deployment processed and pipelines",
            "Collaborate with internal and external partners to design, develop and integrate with APIs that empower users to share and utilize their medical data in partner systems",
            "Design and implement unit testable code that is highly maintainable solutions",
            "Collaborate with both internal and external team members to shape and define API contracts",
            "Ensure performance, uptime, and scale, maintaining high standards of code quality and thoughtful design",
            "Create software architecture and design documentation for the supported solutions and overall best practices and patterns",
            "Support solution groups with technical planning, design, and code reviews including peer code review of Pull Request",
            "Provide Architecture and Technical Knowledge training and support for the solution groups",
            "Develop good working relations with the other solution teams and groups, such as Engineering, Marketing, Product, Test, QA",
            "Stay current with emerging trends, making recommendations as needed to help the organization innovate",
          ],
          Benefits: [
            "Career development with an international company where you can grow the career you dream of",
            "Free medical coverage for employees* via the Health Investment Plan (HIP) PPO",
            "An excellent retirement savings plan with high employer contribution",
            "Tuition reimbursement, the Freedom 2 Save student debt program and FreeU education benefit - an affordable and convenient path to getting a bachelor’s degree",
            "Participants who complete a short wellness assessment qualify for FREE coverage in our HIP PPO medical plan",
            "Free coverage applies in the next calendar year",
            "The base pay for this position is $90,700.00 – $181,300.00",
            "In specific locations, the pay range may vary from the range posted",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_occupational_categories: ["Research & Development"],
        job_naics_code: "325412",
        job_naics_name: "Pharmaceutical Preparation Manufacturing",
      },
      {
        employer_name: "Upwork",
        employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
        employer_website: "http://www.elance.com",
        employer_company_type: "Computer Services",
        job_publisher: "Upwork",
        job_id: "pl9K88Y2GU8NE8CdAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Fulltime Senior React Developer (React 18, Hooks, Rest)",
        job_apply_link:
          "https://www.upwork.com/freelance-jobs/apply/Fulltime-Senior-React-Developer-React-Hooks-Rest_~01b2bfb6e63a3ddb9c/",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6833,
        apply_options: [
          {
            publisher: "Upwork",
            apply_link:
              "https://www.upwork.com/freelance-jobs/apply/Fulltime-Senior-React-Developer-React-Hooks-Rest_~01b2bfb6e63a3ddb9c/",
            is_direct: true,
          },
        ],
        job_description:
          'We are a young startup looking for a senior React developer for maildroppa.com.\n\nOur app communicates over Rest(Json) with a Java Backend.\n\nI am a well-known Java influencer, speaker and senior Java backend developer with over 20 years of experience. I am working on the Java backend, and you would work both with me and my other React developer and my designer, both from Ukraine.\n\nAs I am a developer, we keep meetings to a minimum. Communication and team play however is very important to us. We use Skype for chat and short video communication, and from time to time I send small videos (Wistia Soapbox) for direct instructions and feedback that you can watch and rewatch any time that suits you.\n\nThis is pretty much greenfield project. We always use the latest and greatest technology, so you should be familiar with:\n\n-React 17.x (happy to move to React 18 asap!)\n\n-Hooks: useReducer(!), useContext, useState, useEffect, useRef, customHooks\n\n-React Router\n\n-Rest APIs\n\n-GIT\n\nThis is a full-time job. We have lots of work for you. 20 hours/week should be the absolute minimum.\n\nPlease note I only work with people from the stated regions and I rarely work with agencies.\n\nTo show me your skills, please send me a few lines (10-20 maybe) of some code that you are proud of, and add some explanation of why you think this is good code. Less is more! Ideally, your code is related to the necessary skills mentioned above. Ideally, send me a link to a public repository, avoid sending me zip files, and remember - less is more.\n\nFinally, to prove that you are able to read and follow instructions to the very end, please put "Unicorn" in the first line of your application.',
        job_is_remote: true,
        job_posted_at_timestamp: 1696500555,
        job_posted_at_datetime_utc: "2023-10-05T10:09:15.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=pl9K88Y2GU8NE8CdAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: null,
        job_offer_expiration_timestamp: null,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 240,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: ["React", "JavaScript"],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "I am a well-known Java influencer, speaker and senior Java backend developer with over 20 years of experience",
            "React 17.x (happy to move to React 18 asap!)",
            "Hooks: useReducer(!), use",
            "React Router",
          ],
        },
        job_job_title: "Senior",
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_naics_code: "541511",
        job_naics_name: "Custom Computer Programming Services",
      },
      {
        employer_name: "Ascendion",
        employer_logo:
          "https://collabera.com/wp-content/uploads/2022/06/Mask-group-2.svg",
        employer_website: "http://www.ascendion.com",
        employer_company_type: null,
        job_publisher: "LinkedIn",
        job_id: "9-knJdP_1ju7oNOCAAAAAA==",
        job_employment_type: "CONTRACTOR",
        job_title: "React Developer",
        job_apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-at-ascendion-3727759326",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.5885,
        apply_options: [
          {
            publisher: "LinkedIn",
            apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-ascendion-3727759326",
            is_direct: false,
          },
        ],
        job_description:
          "About Ascendion\n\nAscendion is a full-service digital engineering solutions company. We make and manage software platforms and products that power growth and deliver captivating experiences to consumers and employees. Our engineering, cloud, data, experience design, and talent solution capabilities accelerate transformation and impact for enterprise clients. Headquartered in New Jersey, our workforce of 6,000+ Ascenders delivers solutions from around the globe. Ascendion is built differently to engineer the next.\n\nhttps://ascendion.com/\n\nDigital Engineering Services and Solutions\n\nDiscover Cutting-edge Digital Engineering Services and Solutions with Ascendion. Elevate your innovation journey with our expert team and unlock the true potential of technology-driven solutions for your business needs.\n\nascendion.com\n\nWe have a culture built on opportunity, inclusion, and a spirit of partnership. Come change the world with us.\n\n• Build the coolest tech for the world’s leading brands.\n\n• Solve complex problems and learn new skills.\n\n• Experience the power of transforming digital engineering for Fortune 500 clients\n\n• Master your craft with leading training programs and hands-on experience.\n\nExperience a community of changemakers!\n\nJoin a culture of high-performing innovators with endless ideas and a passion for tech. Our culture is the fabric of our company, and it is what makes us unique and diverse. The way we share ideas, learning, experiences, successes, and joy allows everyone to be their best at Ascendion.\n\nAbout the role:\n\nJob Title: Front End Engineer\n\nKey Responsibilities:\n• Fullstack developer, be able to do front end\n• 5+ years working exp (work independently, need 3 min in development with react libraries)\n• Be able to work independently\n• Understand browser and integrate with backend services\n• Exp Building complex software\n• Be able to do full integration tests\n• Communicating with user, work with UX team\n• Strong verbal and written communication\n\nMinimum Qualifications:\n• react, Typescript, node.js,\n• database technologies\n• Troubleshooting core libraries\n• Portfolio\n\nLocation: Seattle (Hybrid)\n\nSalary Range: The salary for this position is between $132,000 – $142,000 annually. Factors that may affect pay within this range may include geography/market, skills, education, experience, and other qualifications of the successful candidate.\n\nBenefits: The Company offers the following benefits for this position, subject to applicable eligibility requirements: [medical insurance] [dental insurance] [vision insurance] [401(k) retirement plan] [long-term disability insurance] [short-term disability insurance] [5 personal day accrued each calendar year. The Paid time off benefits meet the paid sick and safe time laws that pertains to the City/ State] [10-15 day of paid vacation time] [6 paid holidays and 1 floating holiday per calendar year] [Ascendion Learning Management System]\n\nWant to change the world? Let us know.\n\nTell us about your experiences, education, and ambitions. Bring your knowledge, unique viewpoint, and creativity to the table. Let’s talk\n\nLet’s talk! Feel free to send your queries to harshiv.mistry@ascendion.com or simply reach out to me at 425-307-4066.\n\nThanks",
        job_is_remote: false,
        job_posted_at_timestamp: 1696360818,
        job_posted_at_datetime_utc: "2023-10-03T19:20:18.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: [
          "paid_time_off",
          "dental_coverage",
          "retirement_savings",
          "health_insurance",
        ],
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=9-knJdP_1ju7oNOCAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2023-11-02T19:20:17.000Z",
        job_offer_expiration_timestamp: 1698952817,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 60,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: null,
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: true,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: 132000,
        job_max_salary: 142000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: {
          Qualifications: [
            "5+ years working exp (work independently, need 3 min in development with react libraries)",
            "react, Typescript, node.js,",
            "database technologies",
            "Troubleshooting core libraries",
            "Bring your knowledge, unique viewpoint, and creativity to the table",
          ],
          Responsibilities: [
            "Build the coolest tech for the world’s leading brands",
            "Solve complex problems and learn new skills",
            "Experience the power of transforming digital engineering for Fortune 500 clients",
            "Master your craft with leading training programs and hands-on experience",
            "Be able to work independently",
            "Understand browser and integrate with backend services",
            "Be able to do full integration tests",
            "Communicating with user, work with UX team",
          ],
          Benefits: [
            "Salary Range: The salary for this position is between $132,000 – $142,000 annually",
            "Benefits: The Company offers the following benefits for this position, subject to applicable eligibility requirements: [medical insurance] [dental insurance] [vision insurance] [401(k) retirement plan] [long-term disability insurance] [short-term disability insurance] [5 personal day accrued each calendar year",
            "The Paid time off benefits meet the paid sick and safe time laws that pertains to the City/ State] [10-15 day of paid vacation time] [6 paid holidays and 1 floating holiday per calendar year] [Ascendion Learning Management System]",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
      },
      {
        employer_name: "Talent Groups",
        employer_logo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQehKfhY7oDYV4VtLSV5gM6MOOLJeYPOV-gjfe&s=0",
        employer_website: null,
        employer_company_type: null,
        job_publisher: "LinkedIn",
        job_id: "8uH-_5517vw589OPAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "React Native Developer",
        job_apply_link:
          "https://www.linkedin.com/jobs/view/react-native-developer-at-talent-groups-3733968696",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.6342,
        apply_options: [
          {
            publisher: "LinkedIn",
            apply_link:
              "https://www.linkedin.com/jobs/view/react-native-developer-at-talent-groups-3733968696",
            is_direct: false,
          },
        ],
        job_description:
          "• 10+ Years of IT Experience.\n• Must to have Skillset : React Native\n• Good to have Skillset : HTML, CSS , Angular\n• Good to have in back end : API – AWS experience",
        job_is_remote: true,
        job_posted_at_timestamp: 1696518047,
        job_posted_at_datetime_utc: "2023-10-05T15:00:47.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=8uH-_5517vw589OPAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2023-11-04T15:00:47.000Z",
        job_offer_expiration_timestamp: 1699110047,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 120,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: null,
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: true,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "10+ Years of IT Experience",
            "Must to have Skillset : React Native",
            "Good to have Skillset : HTML, CSS , Angular",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113200",
        job_onet_job_zone: "4",
      },
      {
        employer_name: "Upwork",
        employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
        employer_website: "http://www.elance.com",
        employer_company_type: "Computer Services",
        job_publisher: "Upwork",
        job_id: "txVLUl_jr6_vWvQTAAAAAA==",
        job_employment_type: "CONTRACTOR",
        job_title:
          "Looking for a React developer specialized in API integration",
        job_apply_link:
          "https://www.upwork.com/freelance-jobs/apply/Looking-for-React-developer-specialized-API-integration_~017268817eb80a4487/",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6833,
        apply_options: [
          {
            publisher: "Upwork",
            apply_link:
              "https://www.upwork.com/freelance-jobs/apply/Looking-for-React-developer-specialized-API-integration_~017268817eb80a4487/",
            is_direct: true,
          },
        ],
        job_description:
          "I'm building an MVP for an image generation website, and we're currently using React 18 for the frontend. We've encountered an issue during development.",
        job_is_remote: true,
        job_posted_at_timestamp: 1696507437,
        job_posted_at_datetime_utc: "2023-10-05T12:03:57.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=txVLUl_jr6_vWvQTAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: null,
        job_offer_expiration_timestamp: null,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: null,
          experience_mentioned: false,
          experience_preferred: false,
        },
        job_required_skills: [
          "React",
          "Node.js",
          "API Integration",
          "API Development",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {},
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_naics_code: "541511",
        job_naics_name: "Custom Computer Programming Services",
      },
      {
        employer_name: "CyberCoders",
        employer_logo:
          "http://res.cloudinary.com/cybercoders/image/upload/v1386025236/CyberCoders%20is%20Acquired%20by%20On%20Assignment%20for%20%24105%20Million.png",
        employer_website: "http://www.cybercoders.com",
        employer_company_type: null,
        job_publisher: "Trabajo.org",
        job_id: "n20gtWeqKVQBcw4QAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "React Developer Remote Job",
        job_apply_link:
          "https://us.trabajo.org/job-1275-20231004-3fcafacac9c2ee9d65fbb6676840d79f",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.4935,
        apply_options: [
          {
            publisher: "Trabajo.org",
            apply_link:
              "https://us.trabajo.org/job-1275-20231004-3fcafacac9c2ee9d65fbb6676840d79f",
            is_direct: false,
          },
        ],
        job_description:
          "REMOTE PST AVAILABLE*\nWe are a growing FinTech startup working towards democratizing credit for over 150 Million people and helping consumers who are regularly denied access to mainstream credit gain access to the means to change their lives. We are backed by the same folks behind Chime, Square, Revolut, Step, & Brex and using their insight to take a radically different approach to traditional credit issuers striving to give a more individualized credit experience for each of our consumers. Our rapidly expanding platform is giving people a chance to use credit responsibly and give them the chance to access other credit options.\nWe are looking to find an execution-focused React-Native Engineer to join our team and continue to help expand on our iOS and Android mobile applications while helping our technology grow and scale with our consumer's growing needs. Work with product stakeholders to create and execute a development strategy to meet project goals and deadlines\n- Collaborate with software engineers and help set code design and development practices\n- Engage with internal and external stakeholders to gain insight on KPIs to improve platform functionality\n- Mentor and guide junior engineers to ensure proper development on project needs\nThe React-Native Engineer must have at least 5 years of software development experience and be familiar with:\n- Solid grasp of TypeScript development on modern iOS and Android platforms with React-Native libraries\n- Modern relational and non-relational database models (MySQL, GrapQL, NoSQL, etc.)\n- Bachelor's Degree in CS or related field\nExperience with FinTech software platforms\n- Knowledge of React/Redux/Next frameworks\n- Flexible Vacation/PTO\n- Medical/Dental/Vision Insurance\n- So, if you are a React Native Engineer - Fintech with experience, please apply today\nReact Native\n\nJavaScript",
        job_is_remote: false,
        job_posted_at_timestamp: 1696448797,
        job_posted_at_datetime_utc: "2023-10-04T19:46:37.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: ["paid_time_off", "dental_coverage", "health_insurance"],
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=n20gtWeqKVQBcw4QAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2023-10-11T00:00:00.000Z",
        job_offer_expiration_timestamp: 1696982400,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 60,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: null,
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: true,
          degree_preferred: true,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "The React-Native Engineer must have at least 5 years of software development experience and be familiar with:",
            "Solid grasp of TypeScript development on modern iOS and Android platforms with React-Native libraries",
            "Modern relational and non-relational database models (MySQL, GrapQL, NoSQL, etc.)",
            "Bachelor's Degree in CS or related field",
            "Experience with FinTech software platforms",
            "Knowledge of React/Redux/Next frameworks",
            "Flexible Vacation/PTO",
          ],
          Responsibilities: [
            "Work with product stakeholders to create and execute a development strategy to meet project goals and deadlines",
            "Collaborate with software engineers and help set code design and development practices",
            "Engage with internal and external stakeholders to gain insight on KPIs to improve platform functionality",
            "Mentor and guide junior engineers to ensure proper development on project needs",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
      },
      {
        employer_name: "Upwork",
        employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
        employer_website: "http://www.elance.com",
        employer_company_type: "Computer Services",
        job_publisher: "Upwork",
        job_id: "nItxaiOV0uC_QxZBAAAAAA==",
        job_employment_type: "CONTRACTOR",
        job_title: "Laravel/React Developer - Contract to Hire",
        job_apply_link:
          "https://www.upwork.com/freelance-jobs/apply/Laravel-React-Developer_~018abef6de44499dc4/",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6833,
        apply_options: [
          {
            publisher: "Upwork",
            apply_link:
              "https://www.upwork.com/freelance-jobs/apply/Laravel-React-Developer_~018abef6de44499dc4/",
            is_direct: true,
          },
        ],
        job_description:
          "We are looking experienced developer with at least 4 years of experience in Laravel and React.\n\nMust:\n\n- Laravel\n\n- Ci/CD\n\n- MySQL\n\n- NoSQL\n\n- Performance\n\n- Unite Tests\n\n- React.js\n\n- Jest test\n\nBe good:\n\n- English B2\n\n- Python experience",
        job_is_remote: true,
        job_posted_at_timestamp: 1696449790,
        job_posted_at_datetime_utc: "2023-10-04T20:03:10.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=nItxaiOV0uC_QxZBAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: null,
        job_offer_expiration_timestamp: null,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 48,
          experience_mentioned: true,
          experience_preferred: false,
        },
        job_required_skills: [
          "PHP",
          "SQL",
          "HTML5",
          "CSS 3",
          "React",
          "Laravel",
          "API",
          "JavaScript",
          "API Integration",
          "Web Application",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "We are looking experienced developer with at least 4 years of experience in Laravel and React",
            "MySQL",
            "NoSQL",
            "React.js",
            "English B2",
            "Python experience",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_naics_code: "541511",
        job_naics_name: "Custom Computer Programming Services",
      },
      {
        employer_name: "Upwork",
        employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
        employer_website: "http://www.elance.com",
        employer_company_type: "Computer Services",
        job_publisher: "Upwork",
        job_id: "gE1GsMVqC40B1qOBAAAAAA==",
        job_employment_type: "CONTRACTOR",
        job_title: "React Developer - Contract to Hire",
        job_apply_link:
          "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01aac2e13a77967c4f/",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6833,
        apply_options: [
          {
            publisher: "Upwork",
            apply_link:
              "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01aac2e13a77967c4f/",
            is_direct: true,
          },
        ],
        job_description:
          "Must know ReactJS, NodeJS, NextJS and NestJS\n\nYou will play a crucial role in designing and developing interactive web applications using React.js. You will work closely with our talented team of developers, designers, and product managers to create user-friendly and visually appealing front-end solutions. Your expertise in React.js will be essential in implementing robust and efficient components that meet our clients' needs.",
        job_is_remote: true,
        job_posted_at_timestamp: 1696335178,
        job_posted_at_datetime_utc: "2023-10-03T12:12:58.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=gE1GsMVqC40B1qOBAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: null,
        job_offer_expiration_timestamp: null,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: null,
          experience_mentioned: false,
          experience_preferred: false,
        },
        job_required_skills: [
          "React",
          "JavaScript",
          "CSS",
          "HTML",
          "Node.js",
          "React Native",
          "Web Development",
          "Web Application",
          "API",
          "CSS 3",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: 10,
        job_max_salary: 45,
        job_salary_currency: "USD",
        job_salary_period: "HOUR",
        job_highlights: {
          Responsibilities: [
            "You will play a crucial role in designing and developing interactive web applications using React.js",
            "You will work closely with our talented team of developers, designers, and product managers to create user-friendly and visually appealing front-end solutions",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_naics_code: "541511",
        job_naics_name: "Custom Computer Programming Services",
      },
      {
        employer_name: "HonorVet Technologies",
        employer_logo: null,
        employer_website: null,
        employer_company_type: null,
        job_publisher: "ZipRecruiter",
        job_id: "SsS76KWN9vYCbbYhAAAAAA==",
        job_employment_type: "CONTRACTOR",
        job_title: "React Developer",
        job_apply_link:
          "https://www.ziprecruiter.com/c/HonorVet-Technologies/Job/React-Developer/-in-Bentonville,AR?jid=3534f77424990800",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.6599,
        apply_options: [
          {
            publisher: "ZipRecruiter",
            apply_link:
              "https://www.ziprecruiter.com/c/HonorVet-Technologies/Job/React-Developer/-in-Bentonville,AR?jid=3534f77424990800",
            is_direct: false,
          },
          {
            publisher: "Salary.com",
            apply_link:
              "https://www.salary.com/job/bits/react-developer-w2/j202305052343015448682",
            is_direct: false,
          },
          {
            publisher: "LinkedIn",
            apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-honorvet-technologies-3623226393",
            is_direct: false,
          },
          {
            publisher: "BeBee",
            apply_link:
              "https://us.bebee.com/job/20230920-d9e69188f11416e16b13ee954e971413",
            is_direct: false,
          },
          {
            publisher: "CareerBuilder",
            apply_link: "https://www.careerbuilder.com/job/J3T7FL6RRBG6SFXBL8Y",
            is_direct: false,
          },
          {
            publisher: "Talent.com",
            apply_link: "https://www.talent.com/view?id=07093dbe170f",
            is_direct: false,
          },
          {
            publisher: "Bentonville, AR - Geebo",
            apply_link:
              "https://bentonville-ar.geebo.com/jobs-online/view/id/1326245218-react-developer-/",
            is_direct: true,
          },
          {
            publisher: "Arkansas Jobs - Tarta.ai",
            apply_link:
              "https://ar.tarta.ai/j/AvE9oYoBcRajQcTjyTet0923-react-developer-in-bentonville-arkansas-at-saxon-global",
            is_direct: false,
          },
        ],
        job_description:
          "Required Skills\nsenior level developer, front end react experience, relocation to Bentonville required, cloud experience (Azure or GCP preferred), enterprise experience, ability to work independently\n\nJob Description\n\nReact Developer\n\nCTH - must be in Bentonville, AR upon start\n\nRequirements: React, Javascript, Cloud experience (Azure or GCP preferred)\n\nSenior level candidates, must be able to work as an independent contributor",
        job_is_remote: false,
        job_posted_at_timestamp: 1683270000,
        job_posted_at_datetime_utc: "2023-05-05T07:00:00.000Z",
        job_city: "Bentonville",
        job_state: "AR",
        job_country: "US",
        job_latitude: 36.372356,
        job_longitude: -94.21021,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=SsS76KWN9vYCbbYhAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2023-11-03T00:00:00.000Z",
        job_offer_expiration_timestamp: 1698969600,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: null,
          experience_mentioned: true,
          experience_preferred: true,
        },
        job_required_skills: null,
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: false,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "CTH - must be in Bentonville, AR upon start",
            "Senior level candidates, must be able to work as an independent contributor",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        job_occupational_categories: ["15-1134.00: Web Developers"],
      },
    ],
  },
  "job-details": {
    status: "OK",
    request_id: "841b7f3c-8aab-4624-a879-33690bfab57f",
    parameters: {
      job_id: "kIPcPX8_lD1LE75OAAAAAA==",
      extended_publisher_details: false,
    },
    data: [
      {
        employer_name: "Fortified Insight",
        employer_logo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1QAHzXXq6yBgMaNVaDvvyryTyTXG849RBEHNl&s=0",
        employer_website: null,
        employer_company_type: null,
        job_publisher: "LinkedIn",
        job_id: "kIPcPX8_lD1LE75OAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "React Developer",
        job_apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-at-fortified-insight-3726956489",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.7608,
        job_description:
          "• Preferred East Coast Hours*\n\nFortified Insight offers a rapidly expanding suite of SaaS products which bring awareness to enterprises around the financial and environmental impact of technology. We are seeking a highly skilled Senior React Developer to join our team and play a crucial role in driving our web development initiatives forward. If you are passionate about creating cutting-edge web applications, solving complex problems, and working in a collaborative team environment, we want to hear from you.\n\nFortified Insight is an equal opportunity employer. Eligible candidates must provide evidence of legal working status for any employer in the U.S.\n\nJob Overview\n\nAs a Senior React Developer at Fortified Insight, you will lead the development of our web application and contribute to the overall architecture and technical direction. You will work closely with our product team, designers, and other developers to deliver high-quality and scalable web solutions.\n\nKey Responsibilities\n\nAs a Senior React developer, you will:\n\nFront-End Development:\n• Lead the development of a dynamic and responsive portal with sophisticated dashboards utilizing the React JS library.\n\nArchitecture and Design:\n• Collaborate with the team to create robust and scalable architecture, ensuring the performance and usability of web applications.\n• Translate Figma designs and wireframes into high-quality code.\n• Develop reusable components and front-end libraries for future use.\n\nSupport:\n• Maintain and enhance the portal based on feedback and analytics.\n• Collaboration:\n• Collaborate closely with cross-functional teams, including designers, backend developers, and stakeholders, to ensure seamless integration and the realization of the envisioned functionalities.\n• Ensure the technical feasibility of UI/UX designs.\n\nOptimization:\n• Optimize applications for maximum speed and scalability, keeping up to date with industry trends and best practices.\n\nCode Review:\n• Review and provide constructive feedback on code written by team members, ensuring code quality and best practices.\n\nTesting:\n• Write and maintain unit tests and end-to-end tests to ensure the reliability of the web application.\n\nDocumentation:\n• Assist in the creation of technical documentation and user manuals.\n\nQualifications\n\nRequired Skills:\n• 5+ years of proven experience in React JS development as a Senior Developer, including a deep understanding of React state management libraries such as Redux or Context API.\n• Experience with popular React workflows (such as Flux or Redux) and routing libraries (like React Router).\n• Proficiency in front-end development languages and tools such as HTML5, CSS3, JavaScript/TypeScript, and webpack.\n• Strong understanding of RESTful APIs and modern authorization mechanisms, such as JSON Web Token.\n• Experience in responsive design principles and implementing complex visualizations using Elastic UI and Apex charts libraries.\n• Familiarity with version control systems (e.g., Git) and collaborative development workflows.\n• Proficiency with browser testing and debugging.\n\nPreferred Skills:\n• Experience with back-end API development frameworks, such as Node.js or ASP.NET is a plus.\n• Previous experience with building dashboards and portals.\n• Knowledge of a CSS pre-processor like SASS or LESS.\n\nPersonal Attributes:\n• Excellent problem-solving skills.\n• Excellent attention to detail.\n• Ability to work autonomously and as part of a team.\n• Excellent communication and interpersonal skills.\n• Excellent English.\n\nWork Environment\n• We are a 100% remote company\n• Occasional travel possible",
        job_is_remote: true,
        job_posted_at_timestamp: 1696266219,
        job_posted_at_datetime_utc: "2023-10-02T17:03:39.000Z",
        job_city: null,
        job_state: null,
        job_country: "US",
        job_latitude: 37.09024,
        job_longitude: -95.71289,
        job_benefits: null,
        job_google_link:
          "https://www.google.com/search?gl=us&hl=en&q=kIPcPX8_lD1LE75OAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=kIPcPX8_lD1LE75OAAAAAA%3D%3D&htidocid=kIPcPX8_lD1LE75OAAAAAA%3D%3D",
        job_offer_expiration_datetime_utc: "2024-03-30T17:03:39.000Z",
        job_offer_expiration_timestamp: 1711818219,
        job_required_experience: {
          no_experience_required: false,
          required_experience_in_months: 60,
          experience_mentioned: true,
          experience_preferred: true,
        },
        job_required_skills: [
          "React.js",
          "API Development",
          "Front-End Development",
          "Redux.js",
          "TypeScript",
          "Responsive Web Design",
          "JavaScript",
          "HTML5",
        ],
        job_required_education: {
          postgraduate_degree: false,
          professional_certification: false,
          high_school: false,
          associates_degree: false,
          bachelors_degree: true,
          degree_mentioned: false,
          degree_preferred: false,
          professional_certification_mentioned: false,
        },
        job_experience_in_place_of_education: false,
        job_min_salary: null,
        job_max_salary: null,
        job_salary_currency: null,
        job_salary_period: null,
        job_highlights: {
          Qualifications: [
            "5+ years of proven experience in React JS development as a Senior Developer, including a deep understanding of React state management libraries such as Redux or Context API",
            "Experience with popular React workflows (such as Flux or Redux) and routing libraries (like React Router)",
            "Proficiency in front-end development languages and tools such as HTML5, CSS3, JavaScript/TypeScript, and webpack",
            "Strong understanding of RESTful APIs and modern authorization mechanisms, such as JSON Web Token",
            "Experience in responsive design principles and implementing complex visualizations using Elastic UI and Apex charts libraries",
            "Familiarity with version control systems (e.g., Git) and collaborative development workflows",
            "Proficiency with browser testing and debugging",
            "Previous experience with building dashboards and portals",
            "Knowledge of a CSS pre-processor like SASS or LESS",
            "Excellent problem-solving skills",
            "Excellent attention to detail",
            "Ability to work autonomously and as part of a team",
            "Excellent communication and interpersonal skills",
            "Excellent English",
          ],
          Responsibilities: [
            "As a Senior React Developer at Fortified Insight, you will lead the development of our web application and contribute to the overall architecture and technical direction",
            "You will work closely with our product team, designers, and other developers to deliver high-quality and scalable web solutions",
            "Lead the development of a dynamic and responsive portal with sophisticated dashboards utilizing the React JS library",
            "Collaborate with the team to create robust and scalable architecture, ensuring the performance and usability of web applications",
            "Translate Figma designs and wireframes into high-quality code",
            "Develop reusable components and front-end libraries for future use",
            "Maintain and enhance the portal based on feedback and analytics",
            "Collaborate closely with cross-functional teams, including designers, backend developers, and stakeholders, to ensure seamless integration and the realization of the envisioned functionalities",
            "Ensure the technical feasibility of UI/UX designs",
            "Optimize applications for maximum speed and scalability, keeping up to date with industry trends and best practices",
            "Review and provide constructive feedback on code written by team members, ensuring code quality and best practices",
            "Write and maintain unit tests and end-to-end tests to ensure the reliability of the web application",
            "Assist in the creation of technical documentation and user manuals",
          ],
        },
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3",
        estimated_salaries: [
          {
            location: "United States",
            job_title: "React Developer",
            publisher_name: "Glassdoor",
            publisher_link:
              "https://www.glassdoor.com/Salaries/react-developer-salary-SRCH_KO0,15.htm",
            min_salary: 84528,
            max_salary: 132328,
            median_salary: 105346,
            salary_period: "YEAR",
            salary_currency: "USD",
          },
          {
            location: "United States",
            job_title: "React Developer",
            publisher_name: "ZipRecruiter",
            publisher_link:
              "https://www.ziprecruiter.com/Salaries/What-Is-the-Average-React-Developer-Salary-by-State",
            min_salary: 82000,
            max_salary: 157000,
            median_salary: 129846,
            salary_period: "YEAR",
            salary_currency: "USD",
          },
          {
            location: "United States",
            job_title: "React Developer",
            publisher_name: "Salary.com",
            publisher_link:
              "https://www.salary.com/research/salary/hiring/react-developer-salary",
            min_salary: 68936,
            max_salary: 88573,
            median_salary: 78160,
            salary_period: "YEAR",
            salary_currency: "USD",
          },
        ],
        apply_options: [
          {
            publisher: "LinkedIn",
            apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-fortified-insight-3726956489",
            is_direct: false,
          },
          {
            publisher: "ZipRecruiter",
            apply_link:
              "https://www.ziprecruiter.com/c/Snakorpio-Group-Inc./Job/[FULLY-REMOTE]-React-Developer/-in-New-York,NY?jid=2ec8dc94a2cf0d1f",
            is_direct: true,
          },
        ],
        employer_reviews: [],
      },
    ],
  },
};
